trigger:
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: test
    displayName: "Run Tests"
    jobs:
      - job: unit_tests
        displayName: "Run Unit Tests"
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - script: pip install pytest==5.3.0 pytest-cov==2.10.1 pytest-xdist==2.1.0
            displayName: "Install Pytest"
          - script: pytest -n auto
            displayName: "Run unit tests"
          - task: PublishTestResults@2
            displayName: "Publish unit test results"
            inputs:
              testResultsFiles: "tests.xml"
              testRunTitle: Test
          - task: PublishCodeCoverageResults@1
            displayName: "Publish code coverage"
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(System.DefaultWorkingDirectory)//coverage.xml"
              reportDirectory: "$(System.DefaultWorkingDirectory)//htmlcov"

  - stage: build
    displayName: "Build wheel file"
    dependsOn:
      - test
    condition: succeeded()
    jobs:
      - job: build_wheel
        displayName: "Build wheel file"
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - script: pip install --upgrade pip setuptools wheel
            displayName: "Install tools"
          - script: python setup.py sdist bdist_wheel
            displayName: "Build wheel file"
          - task: CopyFiles@2
            inputs:
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "dist"
              publishLocation: "Container"